apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "efs"  
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-073d77123471b2917
    volumeAttributes:
      path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-efs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "efs"    
  resources:
    requests:
      storage: 1Gi


